### ISSUE TITLE
Issues with importing models

### ISSUE THREAD

**Issue by rploeg** [Azure/opendigitaltwins-smartcities#23]
Hello,

I have successful imported several models from this repo, but I am stuck at the "devices". I get an error when I try to add the deviceModel.json to ADT:

![image](https://user-images.githubusercontent.com/49752333/109413317-054a7180-79ad-11eb-9604-7331c61f6196.png)

But the device category is already imported and others references are not there in the model. For example when I try to import the device model:

![image](https://user-images.githubusercontent.com/49752333/109413546-4db65f00-79ae-11eb-9347-76eca2ccef55.png)

Am I missing totally something else?

**Comment by JMayrbaeurl** [comment]
This seems to be a bug! According to [DTDL v2](https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#digital-twin-model-identifier) DTMIs are case-sensitive. The used schema reference used here is 'dtmi:digitaltwins:ngsi_ld:city:deviceCategory;1' but in ./Ontology/crossdomain/deviceCategory.json the id 'dtmi:digitaltwins:ngsi_ld:city:DeviceCategory;1' gets used.

**Comment by JMayrbaeurl** [comment]
Just checked all models with DTDL validator. 5 files with errors. Provided PR #25

**Comment by rploeg** [comment]
Thanks!

**Comment by JMayrbaeurl** [comment]
PR is now merged. Please try again!

**Comment by miriambrus** [comment]
Thanks @rploeg for reporting the issue and @JMayrbaeurl for fixing! @rploeg let us know if you are still getting issues. Closing the issue as resolved for now!

**Comment by miriambrus** [comment]
Resolved
