### ISSUE TITLE
Wrong schema for property dateObserved in dtmi:digitaltwins:ngsi_ld:city:Device;1

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/opendigitaltwins-smartcities#24]
Why is the schema type 'double' used for the property 'dateObserved' in 'dtmi:digitaltwins:ngsi_ld:city:Device;1'? See file ./Ontology/crossdomain/device.json. Should this be replaced by 'dateTime'?

**Comment by ACSirus** [comment]
Thanks @JMayrbaeurl for the feedback! This has been changed accordingly.
